general {
    hide_cursor = true
    ignore_empty_input = true
    no_fade_in = false
}

background {
    path = ~/media/wallpaper.jpg
    blur_passes = 3
    blur_size = 8
}

shape {
    monitor =
    size = 280, 55
    color = rgba(255, 255, 255, .1)
    rounding = -1
    border_size = 0
    border_color = rgba(253, 198, 135, 0)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, -130
    halign = center
    valign = center
}

input_field {
    size = 200, 50
    position = 0, -80
    monitor =
    dots_center = true
    fade_on_empty = false
    font_color = rgb(202, 211, 245)
    inner_color = rgb(91, 96, 120)
    outer_color = rgb(24, 25, 38)
    outline_thickness = 5
    placeholder_text = "i ate a cat"
    shadow_passes = 2
}
